CREATE DATABASE college;

USE college;

CREATE TABLE student (
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);

INSERT INTO student VALUES(1,"JAHNAVI",19);
INSERT INTO student VALUES(2,"AMIT",44);
